### ISSUE TITLE
폐쇄망에서 시험해 볼 수 있게 모델 다운로드 할 수 있도록 하는 방법을 공유해주실수 있나요?

### ISSUE THREAD

**Issue by bbangpan** [kakaobrain/pororo#14]
## Describe a requested feature

좋은 라이브러리 공유 감사드립니다. 저희 시험 환경이 폐쇄망인데, 설치 후에 언어 모델을 다운로드 받는 부분이 있더라고요. 외부망에서 다운로드 받아서 어떤 파일을 옮기면 될지 간단히 문의드립니다

감사합니다

## Expected behavior

```python
>>> a = Foo()
>>> a.predict()
```

**Comment by hyunwoongko** [comment]
외부망이 가능한 곳에서 모델을 다운로드 받으시면 루트 경로에 `.pororo` 폴더가 생깁니다. 
우분투의 경우 `/root/.pororo` 윈도우의 경우 `C:\Users\YOUR_NAME\.pororo`에 저장됩니다. 
이 폴더를 폐쇄망에서 사용하는 루트 경로에 옮기시면 정상작동 할 것 같네요.

**Comment by bbangpan** [comment]
말씀하신 내용 등 참조해서 보니 nltk_data도 같이 옮겨줘야 하는 것으로 보이기도 합니다.

예컨데 

$ cd ~
$ tar cvfz_model.tgz .pororo/ nltk_data/

해서 옮긴 후 압축풀기하면 될것 같아요. 다른 분들께도 도움이 되시기를
답변 감사드립니다.

**Comment by Huffon** [comment]
@bbangpan 
좋은 경험 공유 감사합니다. 다른 분들께도 많은 도움이 될 것 같습니다.
