### ISSUE TITLE
(Question) fairseq wav2vec2.0 모델 호환

### ISSUE THREAD

**Issue by 21jun** [kakaobrain/pororo#23]
pororo의 asr이 fairseq wav2vec 으로 구현되어있는데, 
이때 모델은 https://github.com/pytorch/fairseq/tree/master/examples/wav2vec 의 가이드를 따라 학습하고
생성된 모델파일(.pt)과 .ltr 파일을 그대로 사용하신건가요?
그렇다면 위 가이드의 wav2vec2.0 을 사용하신건지 wav2vec 을 사용하신건지 궁금합니다. 

목표는 fairseq를 이용해 wav2vec 을 학습하고 pororo를 통해 inference 해보려고 합니다.
```
wav2vec.ko.pt
ko.ltr.txt
```
/root/.pororo/misc 에 존재하는 위 파일들이 어떻게 생성된 것인지 궁금합니다.

멋진 라이브러리를 공개해주셔서 정말 감사합니다!

**Comment by kbumsik** [comment]
안녕하세요. 저도 딱 이 질문 올리려고 했는데 먼저 올리셨네요.
문서에는 [KsponSpeech 스피치 코퍼스](https://www.mdpi.com/2076-3417/10/19/6936)가 언급되었는데, 본문에 링크된 가이드에 따라 해당 코퍼스를 학습시킨건지 저도 궁금합니다.
또한 재확인 차원에서, 해당 pre-trained model의 재배포 관련 라이센스도 소스코드와 동일한 아파치2.0이 적용되는지 알고 싶습니다.

+1 대신에 좀 더 길게 적어봅니다. 마침 음성인식 라이브러리를 찾고 있었는데 공개해 주셔서 감사합니다!

**Comment by sooftware** [comment]
안녕하세요 @21jun 님.  
Wav2vec 2.0 모델을 사용했습니다. 말씀해주신대로 Fairseq에서 제공하는 코드 및 가이드를 따라서 학습을 진행했습니다.  
추가적으로 궁금하신게 있으시면 언제든지 질문해주세요.

**Comment by sooftware** [comment]
@kbumsik 예 KsponSpeech를 이용해서 가이드에 따라 해당 코퍼스를 학습시켰습니다.  
모델 재배포 관련해서는 확인 후 코멘트 드리겠습니다.

**Comment by 21jun** [comment]
@sooftware 답변 정말 감사합니다!

한가지 더 궁금한점이 생겨 질문드립니다.

pororo에서 제공하는 모델은 `.pt` 파일을 불러왔을때, `pretrain_args` 를 포함하고 있는데, 
이 변수는 어떻게 생성된 것인지요?

https://github.com/kakaobrain/pororo/blob/2476fa58371a2be2bf8463b9c25b68897edbf8b8/pororo/models/wav2vec2/recognizer.py#L64

위 코드에 중단점을 설정하고 디버깅 해봤습니다. 


pororo의 en 모델
![image](https://user-images.githubusercontent.com/29483429/106991504-b5b3c400-67b9-11eb-981a-fe888fb69902.png)

fairseq 에서 제공하는 librispeech 로 학습된 [pretrained 모델](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#pre-trained-models)
![image](https://user-images.githubusercontent.com/29483429/106991543-c9f7c100-67b9-11eb-8ae9-e06449a1da82.png)


fairseq에서 제공하는 pretrained 모델을 그대로 pororo에 적용해 보려고 하니, `pretrain_args` 가 포함되어 있지 않아 Key Error가 발생했습니다. 

모델을 저장할때 따로 적용해주신 것 인지, 아니면 fairseq을 이용해 fine-tuning 까지 마치면 [Fine tuning with CTC](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#fine-tune-a-pre-trained-model-with-ctc) `pretrain_args`가 생성되는지 여쭤보고 싶습니다.

다시한번 감사합니다. 😆

**Comment by sooftware** [comment]
@21jun Wav2vec 2.0 학습 이후 체크포인트 로드시에, pretrain 모델 경로에 프리트레인 모델의 체크포인트가 있어야 되는 불편함이 있어서 체크포인트 및 코드를 수정하여 사용했습니다. 불필요하다고 판단된 체크포인트의 데이터는 삭제했기 때문에, fairseq에서 기본적으로 저장하는 체크포인트와는 차이가 있습니다.

**Comment by bernardscumm** [comment]
@kbumsik 
언급해주신 모델은 `Apache License  2.0` 에 따라 사용해 주시면됩니다.
참고로 3rd Party 모델도 포함하고 있어서 모델 마다 적용되는 라이선스가 다를 수 있습니다.

**Comment by kbumsik** [comment]
@bernardscumm 빠르게 확인해 주셔서 감사합니다 :)

**Comment by 21jun** [comment]
@sooftware 

답변 감사드립니다.
확인해보니 fairseq에서 제공하는 모델을 불러와서  `args` 내부에 `w2v_args`를 `pretrain_args` 대신 사용하니 정상적으로 동작하네요. 

혹시 저와 같은 고민을 하신 분들을 위해 코드 남겨놓겠습니다.

https://github.com/kakaobrain/pororo/blob/2476fa58371a2be2bf8463b9c25b68897edbf8b8/pororo/models/wav2vec2/recognizer.py#L59

`w2v["pretrain_args"] → w2v['args'].w2v_args `

```python
  def _load_model(self, model_path: str, device: str, target_dict) -> list:
        w2v = torch.load(model_path, map_location=device)
        model = BrainWav2VecCtc.build_model(
            w2v["args"],
            target_dict,
            # 수정
            w2v["args"].w2v_args,
        )
        model.load_state_dict(w2v["model"], strict=True)
        model.eval().to(self.device)
        return [model]
```

**Comment by 21jun** [comment]
fairseq 버전 관련 문의

안녕하세요. 매번 답변 감사드립니다.

pororo asr 의 wav2vec2.0 모델을 학습하실때 사용한 fairseq의 commit id를 여쭤보고 싶습니다.

현재 fairseq의 master branch의 코드는 wav2letter++가 아닌 flashlight 바인딩을 사용하는데, (wav2letter가 flashlight로 통합됨에 따라)

이러한 문제로 현재 fairseq 버전에서 학습한 모델이 pororo에 호환되지 않는 것 같습니다.

번거로우시더라도 한번 확인해 주시면 정말 감사하겠습니다!

**Comment by sooftware** [comment]
제가 더 이상 카카오 브레인 소속이 아니여서, 자세한 답변은 어려울 것 같습니다만, 당시에 fairseq 0.10.0 버젼이 배포되기 직전 정도에 사용했던 걸로 기억하고 있습니다.

**Comment by 21jun** [comment]
@sooftware 감사합니다. 2020년 11월 이전 버전으로 시도해보겠습니다!
