### ISSUE TITLE
한국어 NER 클래스에서 apply_wsd 인자 활용

### ISSUE THREAD

**Issue by ByungjunKim** [kakaobrain/pororo#24]
## How to reproduce

```python
```

## Environment

- OS : Ubuntu 16.04
- Python version : 3.7
- CPU/GPU : Intell Zeon / V100
- Misc. :

안녕하세요 좋은 패키지 만들어주셔서 이자리를 빌어 감사드립니다.
한국어 NER 함수를 써보고 있는데요. 한국어는 'apply_wsd' 인자를 추가할 수 있다고 써있어서 아래처럼 똑같이 실행을 했습니다.

`ner("손흥민은 28세의 183 센티미터, 77 킬로그램이며, 현재 주급은 약 3억 원이다.", apply_wsd=True)
`
그런데 apply_wsd 인자가 없는 것과 똑같은 결과가 나오더군요. 어떤 문제일까요?

감사합니다.

**Comment by Huffon** [comment]
현재 기능 추가 이후, 버전 배포를 진행하지는 않은 상황입니다. 다음 주 중에 새로운 버전으로 배포를 할 예정이며, 그 전에 사용을 원하시면 소스 코드를 클론해서 로컬 설치 후 활용하실 수 있습니다. 감사합니다 😄

**Comment by ByungjunKim** [comment]
아이고 제가 너무 앞서갔군요. 이렇게 좋은 패키지를 보니 다 써보고 싶은 마음에.. 
그저 감사할 뿐입니다. 연구와 수업에 큰 도움이 됩니다.
