### ISSUE TITLE
"bullet-point summarization" task에 관한 질문입니다.

### ISSUE THREAD

**Issue by jaehyeongAN** [kakaobrain/pororo#26]
Text Summarizaion 태스크 중 bullet-point summarization을 사용해보면서 궁금한 점이 생겨 질문드립니다~

[example_text_1.txt](https://github.com/kakaobrain/pororo/files/5942022/example_text_1.txt) 해당 텍스트를 실행하였을 때,
아래와 같은 결과가 나왔고,
```
['46억년 전에 형성된 원시 지구', ' 태양계가 형성되던 시점과 때를 같이', ' 원시 지구는 바깥부분 완전히 녹은 상태를 경험하게 되면서 성장']
```

[example_text_2.txt](https://github.com/kakaobrain/pororo/files/5942026/example_text_2.txt) example_text_1.txt에 3문단 정도가 더 추가된 내용의 텍스트를 실행하였을 때 위와 동일하게 아래와 같은 결과가 나왔습니다.
```
['46억년 전에 형성된 원시 지구', ' 태양계가 형성되던 시점과 때를 같이', ' 원시 지구는 바깥부분 완전히 녹은 상태를 경험하게 되면서 성장']
```

**Q1. 위와 같이 더 많은 텍스트가 추가되었음에도 결과값에 큰 영향이 없는 이유가 무엇인지 궁금합니다. (앞 문단의 point만 잡는 느낌??)**

**Q2. 여러 예시를 테스트 해보니 대략 summarization return 값이 2-3개 문장으로 나오는 듯한데, 모델 학습 시 target sentence 자체가 2~3개 정도로 학습되어서 그런 것인지 궁금합니다.**

**Comment by hyunwoongko** [comment]
A1. Bullet Summary에 앞서서 긴 글을 Extractive Summary를 수행해서 3문장정도로 압축한 뒤에 Bullet Summary를 생성하기 때문에, Extractive Summary 과정에서 동일한 문장이 추출되었다면, Bullet Summary의 출력 결과도 같습니다.

A2. Target Sentence가 2 ~ 5개 문장정도로 학습되었구요. 아마 2 ~ 3 문장으로 출력되는 결과가 많을 거에요. (Training Dataset을 그렇게 구성했습니다.)

**Comment by jaehyeongAN** [comment]
Extractive Summary의 output을 Bullet Summary의 input으로 사용하고 있던 거군요! 그래서 문단이 많더라도  key sentences가 동일하면 같은 결과가 나왔던 거구요~ 이해가 되었습니다👍 응용 방법을 생각해봐야겠네요~ 감사합니다.🙏
