### ISSUE TITLE
한국어 NER에서 추가 학습데이터 적용

### ISSUE THREAD

**Issue by ByungjunKim** [kakaobrain/pororo#32]
## Describe a requested feature
한국어 NER에서 사용자가 기존 데이터에 추가 학습데이터(dict)를 삽입
-

## Expected behavior

https://kakaobrain.github.io/pororo/tagging/ner.html#pororo.tasks.named_entity_recognition.PororoBertCharNer
apply_dict 함수로 모두의 말뭉치를 학습을 하는데, 이때 모두의 말뭉치에 추가 학습데이터를 삽입해서 학습이 가능할까요?

pororo를 통해 정말 많은 분석과 교육이 가능할 것으로 생각합니다. 당장 이번학기 부터 바로 교육과 연구에 적용하려하는데요.
만들어주셔서 감사합니다.

**Comment by Huffon** [comment]
안녕하세요 !
먼저 `apply_dict` 함수는 학습을 위한 함수가 아니라는 점을 정정해드립니다.
`apply_dict` 함수는 기존 **LOCATION**, **TERM**, **CIVILIZATION** 등의 넓은 의미의 카테고리로 **추론**된 결과에 1:1 매칭을 통해 세분류를 지정해주는 방식으로 동작합니다.

`apply_dict` 함수에서 참조하는 파일은 아래와 같은 엔트리를 지니고 있습니다.

```
LOCATION        country 벨기에
LOCATION        country 벨기에 왕국
LOCATION        country 벨기에왕국
LOCATION        country 포르투갈
LOCATION        country 중화인민공화국
LOCATION        country 중국
LOCATION        country 중공
LOCATION        country 브라질
...
```

`apply_dict` 함수의 적용 전후 결과는 아래와 같습니다.

```python
# w/o `apply_dict`
[('저는', 'O'), (' ', 'O'), ('중국', 'LOCATION'), (' ', 'O'), ('사람입니다.', 'O')]
# with `apply_dict`
[('저는', 'O'), (' ', 'O'), ('중국', 'COUNTRY'), (' ', 'O'), ('사람입니다.', 'O')]
```

현재 `apply_dict` 기능이 `True`로 설정되어 있어, 파일에 등록된 모든 엔트리들은 세분류로 대체되어 보여지고 있다고 이해해주시면 될 것 같습니다.
세분류를 추가하는 기능 정도로는 활용하실 수 있으십니다.

**Comment by ByungjunKim** [comment]
친절한 답변 감사합니다.
wiki.ko.items 파일에 추가를 해보니 추가된 단어도 잘 인식하네요. 정말 정말 감사합니다.
수업에 큰 도움이 되겠습니다.

**Comment by hsChoi92** [comment]
> 친절한 답변 감사합니다.
> wiki.ko.items 파일에 추가를 해보니 추가된 단어도 잘 인식하네요. 정말 정말 감사합니다.
> 수업에 큰 도움이 되겠습니다.

wiki.ko.items 파일에 단어를 추가하려고 하는데 어디서 찾을 수 있나요?

**Comment by ByungjunKim** [comment]
일단 wiki.ko.items 파일에 추가해도 학습이 되는 건 아닙니다.  따라서 인식하지 못하는 경우가 대부분이라 큰 의미가 없습니다.
또한 해당 파일은 파이썬 패키지 설치 폴더를 찾아보면 있습니다.
