### ISSUE TITLE
Text Summarization에 "kobart.base.ko.summary" Model에 관한 질문입니다.

### ISSUE THREAD

**Issue by dlawlsgud** [kakaobrain/pororo#33]
해당 Model을 직접 구현해보고 성능을 평가해보려고 합니다. 
Dacon_Dataset과 AI HUB_Dataset에 대하여 train/valid/test data를 어떤 비율로 나눴는지 그리고 Rouge Score를 구할 때 각 토큰을 어떻게 구분했는지에 대해 알 수 있을까요?
감사합니다~

**Comment by hyunwoongko** [comment]
데이콘 training 데이터셋 + AI hub 데이터셋 (1차 릴리즈버전, 현재는 비공개 상태)을 전부 training 데이터로 사용하고, 데이콘 test 데이터셋으로 평가했구요. tokenizer는 KoBART 토크나이저를 이용해서 분절한 상태로 `rouge` 패키지를 이용해서 성능을 측정했습니다.

**Comment by dlawlsgud** [comment]
네 답변 감사합니다. 
공개해주신 모델들이 연구하는데 있어 많은 도움이 되었습니다. 감사합니다.

**Comment by hyunwoongko** [comment]
@dlawlsgud 다시 확인해보니, 데이콘 테스트 셋이 아니라 데이콘 training set에 있는 마지막 1000개 문서를 이용해서 테스트를 진행했습니다. 참고 부탁드릴게요~

**Comment by dlawlsgud** [comment]
넵넵 감사합니다!
