### ISSUE TITLE
TTS 모듈 로드 중 ModuleNotFoundError: No module named 'pororo.models.tts.hifigan'

### ISSUE THREAD

**Issue by cheesama** [kakaobrain/pororo#34]
## Environment

- OS : ubuntu 20.04
- Python version : 3.8
- Misc. :

안녕하세요 개발해주신 핫한 패키지 써보려고 하는데요 (좋은 패키지 만들어주셔서 감사합니다 ㅎㅎ)

해당 모듈 위치에 __init__.py가 누락된 것이 아닌지 조심스레 추측해 봅니다. 마스터 브랜치 기준으로 확인 부탁드릴게요^^

## FAQ

- [Windows Support (fairseq)](https://github.com/kakaobrain/pororo/issues/15#issuecomment-772417976)

**Comment by sooftware** [comment]
@cheesama 이슈 남겨주셔서 감사합니다. 해당 폴더에 __init__.py 추가했습니다.

**Comment by sooftware** [comment]
아직 pypi로는 배포하지 않아서 로컬로 새로 인스톨하신 후 사용하셔야 될 것 같습니다.
