### ISSUE TITLE
Typo on age_suitability.html

### ISSUE THREAD

**Issue by SDSTony** [kakaobrain/pororo#39]
I think there is a typo on `age_suitability.html`. The word `nudiy` in the emotion type table should be `nudity`. 

I'm not sure if this is the appropriate way to fix the published web documents, but I've created a PR #38 which edits the `html` file directly. 

Feel free to close the PR if it's inappropriate. 

Thanks for opening up an awesome library.

**Comment by Huffon** [comment]
Thanks @SDSTony !
