### ISSUE TITLE
Wav2Vec2.0을 학습시 사용한 dataset 분량에 대해

### ISSUE THREAD

**Issue by Jackson-Kang** [kakaobrain/pororo#48]
안녕하세요, 좋은 코드 공유해주셔서 감사드립니다.

혹시 Wav2Vec2.0을 pretrain / finetune할때 사용하신 KsponSpeech dataset의 양과 어떤 샘플을 pretrain/finetune에 사용하셨는지 알려주실 수 있나요?

**Comment by sooftware** [comment]
pretrain, finetune 모두 KsponSpeech 트레이닝 데이터 전체를 사용했습니다.

**Comment by Jackson-Kang** [comment]
@sooftware 

답변 감사드립니다.
많은 도움이 되었습니다.
