### ISSUE TITLE
mirror.kakao.com/pypi 에 pororo 패키지가 없음

### ISSUE THREAD

**Issue by MaybeS** [kakaobrain/pororo#57]
pororo 관련은 아니지만 혹시나해서 (kakao pypi mirror issue tracker는 찾을 수 없어서 + 같은계열사라 혹시나해서) 올려봅니다.

- http://mirror.kakao.com/pypi/simple/pororo 패키지를 찾을 수 없습니다.
- 따라서 기본 pypi index를 mirror.kakao.com 으로 사용할 경우 아래와 같이 index를 추가해야합니다

```
pip install pororo -i https://pypi.org/simple
```

## Environment

- OS : Windows 10 / WSL Ubuntu 18.04 LTS
- Python version : 3.8
- Misc. :

<br>

## FAQ

- [Windows Support (fairseq)](https://github.com/kakaobrain/pororo/issues/15#issuecomment-772417976)

**Comment by huntrax11** [comment]
@MaybeS 카카오 미러 운영부서에 전달하였고, 현재 복구되었습니다.
제보 감사합니다.
