### ISSUE TITLE
Ubuntu 20.04, Korean tokenizer issue: ModuleNotFoundError: Please install python-mecab-ko with: `pip install python-mecab-ko`

### ISSUE THREAD

**Issue by htk-kevin** [kakaobrain/pororo#68]
## Environment

- OS : Ubuntu 20.04
- Python version : 3.8 (also tried with 3.7)
- Misc. : (jupyter-notebook, pycharm)

<br>

## Issue
Thanks for your great works.

I've successfully installed (and import) the Pororo module.
However, it keeps on showing the **ModuleNotFoundError issue** while I was trying to use the Korean pororo tokenizer. (It does not happen while using English tokenizers.)

Here is the error log that I've encountered,
```
"Please install python-mecab-ko with: `pip install python-mecab-ko`"
ModuleNotFoundError: Please install python-mecab-ko with: `pip install python-mecab-ko`
```

As said in this error log, I've tried to install the 'python-mecab-ko' on my computer.
However, it keeps on failing due to the _"ERROR: Command errored out with exit status 1:"_ issue. 

Besides, I've double-checked the other pip list but, I've already installed the mecab, konlpy, pororo, mecab-python, etc. successfully.

Is there something I have to install more?
Or is this a compatibility problem with my Debian version?
(I presume that it might be a package issue in python-mecab-ko...but not sure about it.)

Hope to hear from you as soon as possible.
Cheers.

<br>

**Comment by coding-Benny** [comment]
Hello. I also had a similar problem.

In my case, I installed the prerequisites by referring to [python-mecab-ko's README](https://github.com/jonghwanhyeon/python-mecab-ko#readme), and the problem was solved. 

If you missed this part, give it a try. Hope this helps.

**Comment by htk-kevin** [comment]
Great!
After updating the Prerequisites(python3-dev, wget),
it works perfectly in my both Pycharm and jupyter environments.

Thanks for your advice :)
