### ISSUE TITLE
tokenizer관련 문구에 대해 질문 드립니다.

### ISSUE THREAD

**Issue by yundo03** [kakaobrain/pororo#69]
## How to reproduce

```python
from pororo import Pororo

abs_summ = Pororo(task="summarization", model="abstractive", lang="ko")
extra_summ = Pororo(task="summarization", model="extractive", lang="ko")

text1 = "20년 4월 8일 자로 아카이브에 올라온 뜨끈뜨끈한 논문을 찾았다. 카카오 브레인에서 한국어 자연어 처리를 위한 새로운 데이터셋을 공개했다는 내용이다. 자연어 추론(NLI)와 텍스트의 의미적 유사성(STS)는 자연어 이해(NLU)에서 핵심 과제. 영어나 다른 언어들은 데이터셋이 몇 개 있는데, 한국어로 된 NLI나 STS 공개 데이터셋이 없다. 이에 동기를 얻어 새로운 한국어 NLI와 STS 데이터 셋을 공개한다. 이전 의 접근 방식에 따라 기존의 영어 훈련 세트를 기계 번역(machine-translate)하고 develop set과 test set을 수동으로 한국어로 번역한다. 한국어 NLU에 대한 연구가 더 활성화되길 바라며, KorNLI와 KorSTS에 baseline을 설정하며, Github에 공개한다. NLI와 STS는 자연어 이해의 중심 과제들로 많이 이야기가 된다. 이에 따라 몇몇 벤치마크 데이터셋은 영어로 된 NLI와 STS를 공개했었다. 그러나 한국어 NLI와 STS 벤치마크  데이터셋은 존재하지 않았다. 대부분의 자연어 처리 연구가 사람들이 많이 쓰는 언어들을 바탕으로 연구  가 되기 때문. 유명한 한국어 NLU 데이터 셋이 전형적으로 QA나 감정 분석은 포함은 되어있는데 NLI나 STS는 아니다. 한국어로 된 공개 NLI나 STS 벤치마크 데이터셋이 없어서 이런 핵심과제에 적합한 한국어 NLU 모델 구축에 대한 관심이 부족했다고 생각한다. 이에 동기를 얻어 KorNLI와 KorSTS를 만들었다."

print('### abs ###')
print(abs_summ(text1))
print('### extractiave ###')
print(extra_summ(text1))
```
# 출력화면
[Korean Sentence Splitter]: Initializing Kss...
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BartTokenizer'. 
The class this function is called from is 'PreTrainedTokenizerFast'.
_###_ abs ###
카카오 브레인에서 한국어로 된 자연어 이해의 중심 과제들로 많이 이야기가 되는 한국어 자연어 처리를 위한 새로운 데이터셋을 공개했다.
_###_ extractiave ###
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
        - 
카카오 브레인에서 한국어 자연어 처리를 위한 새로운 데이터셋을 공개했다는 내용이다. 이에 동기를 얻어 새로운 한국어 NLI와 STS 데이터 셋을 공개한다. 한국어 NLU에 대한 연구가 더 활성화되길 바라며, KorNLI와 KorSTS에 baseline을 설정하며, Github에 공개한다.

## 해결하고 싶은 문구
출력 문구1)
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BartTokenizer'. 
The class this function is called from is 'PreTrainedTokenizerFast'.

출력 문구2)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

포로로 부분에서는 코드를 해당 코드를 찾을 수 없어 올립니다.
요약기능에 대해서는 출력이 잘 되지만 신경쓰이는 부분이라 올려 봅니다.
이 문구들을 안보고 싶습니다ㅠ

## Environment

- OS : Ubuntu 16.04 LTS(Ubuntu)
- Python version : 3.8
- CPU/GPU :  CPU: Intel Xeon Processor (Skylake, IBRS)  GPU: RTX6000 *2
- Misc. : CUDA 10.2

**Comment by coding-Benny** [comment]
안녕하세요!

올려주신 코드를 실행시켜보니 첫 번째 로그는 아래 코드에서 발생해서
```python
abs_summ = Pororo(task="summarization", model="abstractive", lang="ko")
```

[이 부분](https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_utils_base.py#L1827-L1832)이 출력되는 것으로 보입니다.
```python
if config_tokenizer_class is not None:
    if cls.__name__.replace("Fast", "") != config_tokenizer_class.replace("Fast", ""):
        logger.warning(
            "The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. "
            "It may result in unexpected tokenization. \n"
            f"The tokenizer class you load from this checkpoint is '{config_tokenizer_class}'. \n"
            f"The class this function is called from is '{cls.__name__}'."
        )
```

로그는 문제 해결에 큰 도움을 주지만 `warning` 이하 레벨은 보지 않기를 원하신다면 다음 코드를 상단에 추가하시면 출력되지 않도록 설정 가능합니다.
```python
import logging
logger = logging.getLogger('transformers.tokenization_utils_base')
logger.setLevel(logging.ERROR)
```

다른 부분에서 혹시나 발생할 수 있는 문제 확인을 위해 해당 logger만 선택적으로 `error` 이상의 로그만 출력하도록 안내해 드렸지만, 모든 `warning` 이하 로그가 뜨는 것을 원치 않으신다면 아래의 코드를 추가하시면 됩니다.
```python
import logging
logging.disable(logging.WARN)
```

두 번째 로그는 제 환경에서는 재현되지 않지만 해결책은 로그에 나와 있듯이 다음 두 가지 부분을 체크해보시면 될 것 같습니다.
> To disable this warning, you can either:
> - Avoid using `tokenizers` before the fork if possible
> - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

동일한 내용이지만 해당 [이슈](https://github.com/huggingface/transformers/issues/5486)에 달린 [답변1](https://github.com/huggingface/transformers/issues/5486#issuecomment-654232343), [답변2](https://github.com/huggingface/transformers/issues/5486#issuecomment-833768404)도 참고하시면 좋을 것 같습니다.

도움이 되었기를 바랍니다 :)

**Comment by hyunwoongko** [comment]
```python
import os

os.environ["TOKENIZERS_PARALLELISM"] = "true
```

이 코드를 추가하시면 됩니다.

**Comment by yundo03** [comment]
자세한 설명까지 너무 감사합니다.
