### ISSUE TITLE
OCR 사용 이슈

### ISSUE THREAD

**Issue by HyuntaeKim95** [kakaobrain/pororo#72]
## Describe a requested feature

- OCR 사용 시(ocr=Pororo(task="ocr", lang="ko") 인터넷이 연결되지 않은 경우 에러 발생
- 설치 (pip install pororo) 시 혹은 설치 후 OCR 관련  필요 데이터를 수동으로 설정할 수 있는 방안이 있을까요?

**Comment by jinmang2** [comment]
#14 해당 이슈 참고해주세요
@HyuntaeKim95

**Comment by HyuntaeKim95** [comment]
좋은 정보 감사합니다.^^
